### ISSUE TITLE
Not compatible with typescript

### ISSUE THREAD

**Issue by liamsorsby** [elastic/apm-agent-nodejs-opentracing#15]
I'm currently looking at using this but I'm unable to due to the lack of types for use with typescript

**Comment by liamsorsby** [comment]
I've raised #16 in hope that it resolves the issues

**Comment by nadilas** [comment]
Can we get a release with this?

**Comment by astorm** [comment]
@nadilas Thanks for the heads up on this -- release PR was made today and tags have been pushed the repo.  NPM publish _may_ delayed as we sort out some permissions issue, but it is coming.

**Comment by nadilas** [comment]
@astorm awesome, thanks a lot!

**Comment by trentm** [comment]
v2.0.1 is out now (https://www.npmjs.com/package/elastic-apm-node-opentracing)
